services:
  zookeeper-0:
    image: zookeeper:3.8.6
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=192.168.1.13:2888:3888;2181 server.2=192.168.2.13:2888:3888;2181 server.3=192.168.3.13:2888:3888;2181
    ports:
    - 2181
    volumes:
    - zookeeper-0:/data
    networks:
      arcus:
        ipv4_address: 192.168.3.13
    restart: always

volumes:
  cassandra-storage-0:
  cassandra-storage-1:
  cassandra-storage-2:
  zookeeper-0:
networks:
  private:

  arcus:
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
      - subnet: 192.168.3.0/24
        gateway: 192.168.3.1
