version: '3'
services:
  cassandra-0:
    image: gcr.io/arcus-238802/arcus/cassandra:latest
    environment:
    - CASSANDRA_SEEDS=cassandra-0
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DC=DC1
    - MAX_HEAP_SIZE=256M
    - HEAP_NEWSIZE=256M
    ports:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
    volumes:
    - cassandra-storage-0:/data
    networks:
      arcus:
        ipv4_address: 192.168.0.10
    deploy:
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 5
        window: 120s
  cassandra-1:
    image: gcr.io/arcus-238802/arcus/cassandra:latest
    environment:
    - CASSANDRA_SEEDS=cassandra-0
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DC=DC1
    - MAX_HEAP_SIZE=256M
    - HEAP_NEWSIZE=256M
    ports:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
    volumes:
    - cassandra-storage-1:/data
    networks:
      arcus:
        ipv4_address: 192.168.0.11
    deploy:
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 5
        window: 120s
  cassandra-2:
    image: gcr.io/arcus-238802/arcus/cassandra:latest
    environment:
    - CASSANDRA_SEEDS=cassandra-0
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DC=DC1
    - MAX_HEAP_SIZE=256M
    - HEAP_NEWSIZE=256M
    ports:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
    volumes:
    - cassandra-storage-2:/data
    networks:
      arcus:
        ipv4_address: 192.168.0.12
    deploy:
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 5
        window: 120s
volumes:
  cassandra-storage-0:
  cassandra-storage-1:
  cassandra-storage-2:

networks:
  private:

  arcus:
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
      - subnet: 192.168.0.1/24
